'use client';

import { useEffect, useRef, useState } from 'react';
import { CalendarDays, CloudUpload, FileText, Image as ImageIcon, Play, Radio, RefreshCw, Settings2, Sparkles } from 'lucide-react';
import { ContentItem } from '../lib/types';
import { TopicSelectionPanel } from './TopicSelectionPanel';

const field = 'w-full rounded-lg border border-[#333] bg-[#0d0d0d] px-3 py-2 text-sm text-gray-200 outline-none focus:border-blue-500';

export function HomeDashboard({ initialItems }: { initialItems: ContentItem[] }) {
  const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10)); const [config, setConfig] = useState<any>(); const [models, setModels] = useState<any[]>([]); const [jobs, setJobs] = useState(initialItems); const [activeId, setActiveId] = useState(initialItems[0]?.id); const [message, setMessage] = useState(''); const upload = useRef<HTMLInputElement>(null);
  const active = jobs.find(job => job.id === activeId) || jobs[0];
  const load = async () => { const response = await fetch('/api/settings'); const data = await response.json(); setConfig(data.config); };
  useEffect(() => { load(); fetch('/api/settings/models').then(r => r.ok ? r.json() : []).then(d => setModels(Array.isArray(d) ? d : d.models || d.data || [])).catch(() => {}); const stream = new EventSource('/api/pipeline/stream'); stream.onmessage = event => { try { const item = JSON.parse(event.data) as ContentItem; setJobs(current => { const at = current.findIndex(job => job.id === item.id); return at < 0 ? [item, ...current] : current.map(job => job.id === item.id ? item : job); }); setActiveId(current => current || item.id); } catch {} }; return () => stream.close(); }, []);
  const save = async (next: any) => { const response = await fetch('/api/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); const data = await response.json(); setMessage(response.ok ? 'Settings saved.' : data.error); if (response.ok) setConfig(next); };
  const update = (fn: (copy: any) => void) => { const next = structuredClone(config); fn(next); void save(next); };
  const importFile = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append('file', file); const response = await fetch('/api/topics/upload', { method: 'POST', body }); const data = await response.json(); setMessage(response.ok ? 'Topic file imported. Refreshing available topics.' : data.error); event.target.value = ''; if (response.ok) window.location.reload(); };
  const regenerate = async () => { if (!active) return; await fetch(`/api/preview/${active.id}/regenerate-image`, { method: 'POST' }); };
  const imageUrl = active?.ai33pro_task_id ? `/api/images/${active.ai33pro_task_id}.png` : null;
  return <div className="min-h-full bg-[#080808] p-4"><div className="mx-auto grid max-w-[1700px] gap-4 xl:grid-cols-[310px_minmax(480px,1fr)_380px]">
    <aside className="rounded-[26px] border border-[#343434] bg-[#10110f] p-5 shadow-2xl xl:sticky xl:top-4 xl:h-[calc(100vh-2rem)] xl:overflow-y-auto"><div className="mb-5 flex items-center gap-2"><Settings2 size={18} className="text-blue-400"/><h1 className="font-semibold text-white">Generation setup</h1></div>{config && <><label className="mb-4 block text-sm text-gray-300">AI model<select className={field} value={config.image_generation.model_id} onChange={e => update(c => c.image_generation.model_id = e.target.value)}><option value={config.image_generation.model_id}>{config.image_generation.model_id}</option>{models.map((model: any) => { const id = model.id || model.model_id || model; return <option key={id} value={id}>{model.name || id}</option>; })}</select></label><div className="mb-4 rounded-xl border border-dashed border-[#454545] bg-black/30 p-3"><img src="/api/template" alt="Reference template" className="h-28 w-full rounded-lg object-contain"/><p className="mt-2 text-xs text-gray-500">Reference template attached as @img1</p></div><label className="mb-4 block text-sm text-gray-300">Image description<textarea readOnly value={config.image_generation.prompt_template} className={`${field} h-44 resize-none leading-5 text-gray-400`}/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm text-gray-300">Aspect ratio<input className={field} value={config.image_generation.model_parameters.aspect_ratio || ''} onChange={e => update(c => c.image_generation.model_parameters.aspect_ratio = e.target.value)}/></label><label className="text-sm text-gray-300">Resolution<input className={field} value={config.image_generation.model_parameters.resolution || ''} onChange={e => update(c => c.image_generation.model_parameters.resolution = e.target.value)}/></label></div><label className="mt-4 flex items-center gap-2 text-sm text-gray-300"><input type="checkbox" checked={config.telegram_sync_enabled} onChange={e => update(c => c.telegram_sync_enabled = e.target.checked)}/><Radio size={16}/> Sync Telegram</label></>}</aside>
    <main className="min-w-0 rounded-[26px] border border-[#343434] bg-[#101010] p-5"><div className="mb-5 flex flex-wrap items-center gap-3 border-b border-[#292929] pb-4"><div><h2 className="font-semibold text-white">Daily content queue</h2><p className="text-xs text-gray-500">The date tags the batch; it does not filter Excel topics.</p></div><label className="ml-auto flex items-center gap-2 rounded-lg border border-[#333] bg-[#171717] px-3 py-2 text-sm text-gray-200"><CalendarDays size={16}/><input type="date" value={date} onChange={e => setDate(e.target.value)} className="bg-transparent outline-none"/></label><input ref={upload} type="file" accept=".xlsx" className="hidden" onChange={importFile}/><button onClick={() => upload.current?.click()} className="flex items-center gap-2 rounded-lg border border-[#333] px-3 py-2 text-sm text-gray-300 hover:bg-[#202020]"><CloudUpload size={16}/>Upload Excel</button></div>{message && <p className="mb-4 rounded-lg border border-[#333] bg-[#171717] p-3 text-sm text-gray-300">{message}</p>}<TopicSelectionPanel plannedDate={date}/><div className="mt-6 border-t border-[#292929] pt-5"><h3 className="mb-3 text-sm font-medium text-gray-200">Pipeline jobs</h3><div className="space-y-2">{jobs.length === 0 ? <div className="rounded-xl border border-dashed border-[#333] p-8 text-center text-sm text-gray-500">Choose topics and start automation to create your first job.</div> : jobs.map(job => <button key={job.id} onClick={() => setActiveId(job.id)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left transition-colors ${active?.id === job.id ? 'border-blue-700 bg-[#171d23]' : 'border-[#292929] hover:bg-[#181818]'}`}><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-black">{job.ai33pro_task_id ? <img src={`/api/images/${job.ai33pro_task_id}.png`} className="h-full w-full rounded-lg object-cover" alt=""/> : <ImageIcon size={18} className="text-gray-600"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-gray-100">{job.generated_title || job.headline || job.topic}</p><p className="text-xs text-gray-500">{job.status.replace(/_/g, ' ')}</p></div><span className="text-xs text-gray-600">{job.planned_date || 'Unplanned'}</span></button>)}</div></div></main>
    <aside className="rounded-[26px] border border-[#343434] bg-[#101010] p-5 shadow-2xl xl:sticky xl:top-4 xl:h-[calc(100vh-2rem)] xl:overflow-y-auto"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold text-white">Post preview</h2><p className="text-xs text-gray-500">Facebook posting details</p></div>{active && <button onClick={regenerate} className="flex items-center gap-1 rounded-lg border border-[#444] px-2 py-1.5 text-xs text-gray-300 hover:bg-[#222]"><RefreshCw size={14}/>Regenerate image</button>}</div>{active ? <><div className="mb-5 flex min-h-56 items-center justify-center overflow-hidden rounded-xl border border-[#333] bg-black">{imageUrl ? <img src={imageUrl} alt="Generated post preview" className="max-h-80 w-full object-contain"/> : <div className="text-center text-sm text-gray-500"><ImageIcon className="mx-auto mb-2"/>Preview will appear here</div>}</div><div className="space-y-4"><label className="block text-xs font-medium uppercase tracking-wide text-gray-500">Facebook title<p className="mt-1 text-sm normal-case tracking-normal text-gray-100">{active.fb_title || active.generated_title || active.headline}</p></label><label className="block text-xs font-medium uppercase tracking-wide text-gray-500">Description<p className="mt-1 whitespace-pre-wrap text-sm normal-case tracking-normal text-gray-300">{active.fb_description || active.generated_description || 'Generating description…'}</p></label><label className="block text-xs font-medium uppercase tracking-wide text-gray-500">Hashtags<p className="mt-1 text-sm normal-case tracking-normal text-blue-400">{active.fb_hashtags || active.generated_hashtags || 'Generating hashtags…'}</p></label><div className="rounded-lg border border-[#333] bg-[#151515] p-3 text-xs text-gray-400"><FileText size={15} className="mr-2 inline"/>Excel Facebook settings are used as per-topic overrides when present.</div></div></> : <div className="flex h-72 flex-col items-center justify-center text-center text-sm text-gray-500"><Sparkles size={26} className="mb-3"/>Select a pipeline job to inspect its preview and Facebook posting details.</div>}</aside>
  </div></div>;
}

