'use client';

import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, CreditCard, Plus, Send, Trash2, Upload } from 'lucide-react';

const field = 'w-full rounded border border-[#3a3a3a] bg-[#151515] px-3 py-2 text-sm text-white outline-none focus:border-blue-500';

export function SettingsPanel() {
  const [config, setConfig] = useState<any>(); const [source, setSource] = useState<any>(); const [models, setModels] = useState<any[]>([]); const [message, setMessage] = useState(''); const input = useRef<HTMLInputElement>(null);
  const load = async () => { const r = await fetch('/api/settings'); const d = await r.json(); setConfig(d.config); setSource(d.topicSource); };
  useEffect(() => { load(); fetch('/api/settings/models').then(r => r.ok ? r.json() : []).then(d => setModels(Array.isArray(d) ? d : d.models || d.data || [])).catch(() => {}); }, []);
  const update = (fn: (c: any) => void) => setConfig((current: any) => { const next = structuredClone(current); fn(next); return next; });
  const save = async () => { const r = await fetch('/api/settings', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(config) }); const d = await r.json(); setMessage(r.ok ? 'Settings saved.' : d.error); };
  const upload = async (e: React.ChangeEvent<HTMLInputElement>) => { const f = e.target.files?.[0]; if (!f) return; const form = new FormData(); form.append('file', f); const r = await fetch('/api/topics/upload', { method: 'POST', body: form }); const d = await r.json(); setMessage(r.ok ? 'Topic file imported.' : d.error); if (r.ok) load(); e.target.value = ''; };
  const credits = async () => { const r = await fetch('/api/settings/credits'); const d = await r.json(); setMessage(r.ok ? `Credits: ${d.balance ?? d.credits ?? JSON.stringify(d)}` : d.error); };
  const telegram = async () => { const r = await fetch('/api/telegram/test', { method: 'POST' }); const d = await r.json(); setMessage(r.ok ? 'Test message sent.' : d.error); };
  if (!config) return <p className="text-gray-400">Loading settings…</p>;
  const regions = Object.entries(config.scheduling.regions) as [string, any][];
  return <div className="space-y-6 pb-10">
    {message && <div className="rounded-lg border border-[#3a3a3a] bg-[#151515] p-3 text-sm text-gray-200">{message}</div>}
    <section className="rounded-xl border border-[#333] bg-[#111] p-5 space-y-3"><h2 className="font-semibold text-white">Topic Source</h2><p className="text-sm text-gray-400">Active file: {source?.activeFile || 'None'} · {source?.remaining ?? 0} unconsumed rows</p><input ref={input} className="hidden" type="file" accept=".xlsx" onChange={upload}/><button onClick={() => input.current?.click()} className="inline-flex items-center gap-2 rounded bg-gray-700 px-3 py-2 text-sm text-white"><Upload size={16}/> Replace topic file</button></section>
    <section className="rounded-xl border border-[#333] bg-[#111] p-5 space-y-3"><h2 className="font-semibold text-white">Image Generation</h2><label className="block text-sm text-gray-300">Model<select className={field} value={config.image_generation.model_id} onChange={e => update(c => c.image_generation.model_id = e.target.value)}><option value={config.image_generation.model_id}>{config.image_generation.model_id}</option>{models.map((m: any) => { const id = m.id || m.model_id || m; return <option key={id} value={id}>{m.name || id}</option>; })}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm text-gray-300">Aspect ratio<input className={field} value={config.image_generation.model_parameters.aspect_ratio || ''} onChange={e => update(c => c.image_generation.model_parameters.aspect_ratio = e.target.value)}/></label><label className="text-sm text-gray-300">Resolution<input className={field} value={config.image_generation.model_parameters.resolution || ''} onChange={e => update(c => c.image_generation.model_parameters.resolution = e.target.value)}/></label></div><button onClick={credits} className="inline-flex items-center gap-2 rounded bg-gray-700 px-3 py-2 text-sm text-white"><CreditCard size={16}/> Check Credits</button></section>
    <section className="rounded-xl border border-[#333] bg-[#111] p-5 space-y-4"><h2 className="font-semibold text-white">Scheduling</h2><div className="grid grid-cols-2 gap-3"><label className="text-sm text-gray-300">Minimum interval (minutes)<input type="number" className={field} value={config.scheduling.min_interval_minutes} onChange={e => update(c => c.scheduling.min_interval_minutes = Number(e.target.value))}/></label><label className="text-sm text-gray-300">Maximum posts / 24h<input type="number" className={field} value={config.scheduling.max_posts_per_24h} onChange={e => update(c => c.scheduling.max_posts_per_24h = Number(e.target.value))}/></label></div>{regions.map(([name, region]) => <div key={name} className="rounded border border-[#333] p-3"><div className="grid grid-cols-2 gap-3"><input className={field} value={name} onChange={e => update(c => { const value = c.scheduling.regions[name]; delete c.scheduling.regions[name]; c.scheduling.regions[e.target.value] = value; })}/><input className={field} value={region.timezone} onChange={e => update(c => c.scheduling.regions[name].timezone = e.target.value)}/></div>{region.peak_hours_local.map((win: string[], i: number) => <div key={i} className="mt-2 flex gap-2"><input className={field} value={win[0]} onChange={e => update(c => c.scheduling.regions[name].peak_hours_local[i][0] = e.target.value)}/><input className={field} value={win[1]} onChange={e => update(c => c.scheduling.regions[name].peak_hours_local[i][1] = e.target.value)}/><button onClick={() => update(c => c.scheduling.regions[name].peak_hours_local.splice(i, 1))} className="text-red-400"><Trash2 size={16}/></button></div>)}<button onClick={() => update(c => c.scheduling.regions[name].peak_hours_local.push(['09:00','11:00']))} className="mt-2 inline-flex items-center gap-1 text-sm text-gray-300"><Plus size={15}/> Add window</button></div>)}</section>
    <section className="rounded-xl border border-[#333] bg-[#111] p-5 space-y-3"><h2 className="font-semibold text-white">Branding</h2><label className="block text-sm text-gray-300">Page name<input className={field} value={config.branding.page_name} onChange={e => update(c => c.branding.page_name = e.target.value)}/></label></section>
    <section className="rounded-xl border border-[#333] bg-[#111] p-5 space-y-3"><h2 className="font-semibold text-white">Telegram</h2><p className="text-sm text-gray-400">Connection is configured by the bot token and admin ID on the server.</p><button onClick={telegram} className="inline-flex items-center gap-2 rounded bg-gray-700 px-3 py-2 text-sm text-white"><Send size={16}/> Send Test Message</button></section>
    <button onClick={save} className="inline-flex items-center gap-2 rounded bg-green-700 px-4 py-2 text-sm font-medium text-white"><CheckCircle2 size={16}/> Save Settings</button>
  </div>;
}
